Added README.rst
ganeshhubale/readit pull request #59
Opened 2018-02-12 06:01 UTC by daivshala

Fix #58 
Added README.rst and Removed README.md

2018-02-12 08:16 UTC, shitalmule04 reviewed
LGTM.

2018-02-12 08:33 UTC, ganeshhubale commented on README.rst
> +
@daivshala 
Add here following lines:
# Installation
```
pip3 install --user readit
```

2018-02-12 08:36 UTC, ganeshhubale commented on README.rst
> +How to Install
@daivshala 
Please update this line by
# How to install source code for development

2018-02-12 08:39 UTC, ganeshhubale reviewed
Please make changes asap.

2018-02-13 09:23 UTC, daivshala commented
@ganeshhubale review the changes for next work

2018-02-16 06:04 UTC, bhavin192 requested changes
Please consider the following changes, nice work!

2018-02-16 06:04 UTC, bhavin192 commented on README.rst
> +   contain the root `toctree` directive.
I think we should remove these 4 lines (1 to 4), as this file is not a root file for our `docs`

2018-02-16 06:04 UTC, bhavin192 commented on README.rst
> +`Licence <https://github.com/ganeshhubale/readit/blob/master/LICENSE>`_
How about removing the link to `License` word form this line? 
@ganeshhubale what do you think?

2018-02-16 06:04 UTC, bhavin192 commented on README.rst
> +.. |Licence| image:: https://img.shields.io/badge/license-GPLv3-yellow.svg?maxAge=2592000
It would be great if we add link to our `LICENSE` file here, so clicking on the badge will open the the LICENSE

2018-02-16 06:04 UTC, bhavin192 commented on README.rst
> +.. |Build Status| image:: https://travis-ci.org/ganeshhubale/readit.svg?branch=master
The Travis CI is at different URL now,

```rst
.. |Build Status| image:: https://travis-ci.org/projectreadit/readit.svg?branch=master
    :target: https://travis-ci.org/projectreadit/readit
```

2018-02-21 13:17 UTC, ganeshhubale submitted a review, later dismissed

2018-02-21 13:17 UTC, ganeshhubale commented on README.rst
> +How to install source code for web development
@daivshala 
It would  be good if we keep it  like **How to install source code for development**

2018-02-21 13:17 UTC, ganeshhubale commented on README.rst
> +``HPPT(S)``                                         requests
@daivshala 
please change it to **HTTP(S)**

2018-02-21 13:28 UTC, ganeshhubale commented
@daivshala 
Please make demo video as short as you can and it would be fine; if you just show **add** and **view** features of a tool for **one** URL. Because all other information is already available in `README` file.

2018-03-01 05:22 UTC, merged

2018-03-01 11:22 UTC, bhavin192 commented
@shitalmule04 I think you should at least read the file before merging, there are still typos in the document