Documentation using sphinx
ganeshhubale/readit pull request #76
Opened 2018-03-24 11:09 UTC by daivshala

Fix #63 
It Contains the following files:
1. index.rst
2. README.rst
3. conf.py
4.MAKEFILE
5. make.bat

2018-03-26 13:58 UTC, ganeshhubale commented
@daivshala 
Please add a description for each method.

2018-04-04 02:58 UTC, shitalmule04 commented on docs/database.rst
> +System modules
@daivshala, please add the small description of the usage of system modules.

2018-04-04 03:05 UTC, shitalmule04 requested changes
@daivshala, Please add the small description of the system modules w. r. t. our project.

2018-04-04 03:05 UTC, shitalmule04 commented on docs/database.rst
> +5. os
@daivshala, Please add the small description of the system modules w. r. t. our project.

2018-04-05 08:50 UTC, ganeshhubale commented
@daivshala 
please add new feature:
- Bookmark multiple URLs:
```
$ readit --export
or
$ readit -e 
```

2018-04-05 11:16 UTC, bhavin192 requested changes
It will be really great if you can split the whole `README.rst` into something like this,

`readit.rst` (Readit, Introduction, Features)  
`installation.rst`  
`usage.rst` (Usage, Examples) 
`get_involved.rst` (How to Contribute, Collaborators)

This will help us to maintain the docs easily

2018-04-05 11:16 UTC, bhavin192 commented on docs/README.rst
> +.. contents::
We already have `index.rst` which has index of all sections also we have index on left side so It will be better if we remove this one.

2018-04-05 11:42 UTC, chkumar246 commented
Add a job to build docs using travis and upload it automatically on readthedocs

2018-04-05 11:57 UTC, bhavin192 commented
> Add a job to build docs using travis and upload it automatically on readthedocs
Merge state
Read the Docs does that job for us. I builds the docs automatically

2018-04-11 12:28 UTC, ganeshhubale commented
@daivshala 
Update docs with new features added.

2018-04-11 13:53 UTC, ganeshhubale commented
@daivshala 
- Please update [ this page](http://readit.readthedocs.io/en/latest/py-modindex.html).
- Because here I am getting the same information from three different modules - **readit.cli**, **readit.__init__**, **readit.database**
- It only shows information about methods available in **readit.database** module.
- It should display information about methods available in each module.

2018-04-12 04:49 UTC, daivshala commented
@ganeshhubale 
Search option in docs is working ,  You should check once again and see properly.

2018-04-12 06:10 UTC, shitalmule04 commented
@daivshala, please correct the word `Pypi` (It should be **PyPI**) from **Installation Section** under the **From a package manager** heading. Also, add `**pip3 install readit**` in the bracket. Usually if user login as root no need to use `--user`.

2018-04-12 06:32 UTC, shitalmule04 commented
@daivshala, Write `PyPI` instead of `Pypi` in the installation chapter under the **From a package manager** section.

2018-04-12 08:27 UTC, ganeshhubale commented
@daivshala 
Please add
- New feature 
    - Bookmark URLs either online or offline

2018-04-23 11:50 UTC, ganeshhubale commented
- Update virtual environment for Python3
- Add features

2018-04-23 11:55 UTC, bhavin192 commented
@ganeshhubale is this PR going to be merged?

2018-04-23 11:59 UTC, ganeshhubale commented
@bhavin192 
yes this will be the last one and PR will be merged

2018-05-08 19:54 UTC, ganeshhubale commented
Thank you

2018-05-08 19:55 UTC, merged