convert CHANGELOG.md to CHANGELOG.rst
ganeshhubale/readit pull request #95
Opened 2018-04-13 09:06 UTC by daivshala

Fix #93
All notable changes to this project will be documented in this file.

2018-04-18 08:01 UTC, ganeshhubale requested changes

2018-04-18 08:01 UTC, ganeshhubale commented on CHANGELOG.rst
> +* User should get information about existed URLs in database (#88)
@daivshala 
Please write about test cases we added in this version,

2018-04-20 02:23 UTC, shitalmule04 requested changes

2018-04-20 02:32 UTC, shitalmule04 approved these changes

2018-04-20 02:32 UTC, shitalmule04 commented
@daivshala, please write appropriate commit messages.

2018-04-23 08:40 UTC, ganeshhubale approved these changes

2018-04-23 09:18 UTC, merged