UpdatedREADME by adding Python Badge and new feature information
ganeshhubale/readit pull request #97
Opened 2018-04-14 11:41 UTC by shitalmule04

Following are the changes in `README.rst`

- Python badge updated from **`2.7, 3.6`** to **`3.6`**
- Added new feature information

    - Tag List

    - Yes/No option

- Corrected typoerror **PyPI**

2018-04-17 19:22 UTC, ganeshhubale requested changes

2018-04-18 09:32 UTC, ganeshhubale commented
@shitalmule04 
please refer this to check if README is well written syntactically or not : https://github.com/pypa/readme_renderer

2018-04-18 09:39 UTC, shitalmule04 commented
@ganeshhubale, Thanks.

2018-04-19 16:13 UTC, ganeshhubale approved these changes

2018-04-19 16:13 UTC, merged